### ISSUE TITLE
Offerup lib no longer available ?

### ISSUE THREAD

**Issue by JoelCCodes** [jgdigitaljedi/gs-scraper#1]
Looks like they removed the offerup lib from NPM? Did you fork this by any chance?

**Comment by jgdigitaljedi** [comment]
Nope. They got hit with a DMCA notice so the library is done. I haven't developed on this in a long while either. I might revisit it at some point, but Offerup can't be part of it since they are actively tracking down and stopping people that are trying to use their endpoints without using their site.

**Comment by JoelCCodes** [comment]
Man thats unfortunate. Cool project you got here!
